# Generated by Django 3.0.5 on 2023-06-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineExam', '0002_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onlineExam.Course'),
        ),
    ]
